### ISSUE TITLE
Vignette for programmatic usage

### ISSUE THREAD

**Issue by ramanshah** [unbit/sftpclone#10]
I am using `sftpclone` for a custom deployment for a small static website with some quirky legacy needs. The library is great, so thanks for that! I had to dig into the codebase a little bit to figure out how to use `sftpclone` programmatically. Is there a bit of documentation or an example for a minimal Python script with usage of this module? If not and if you are interested in having this kind of documentation, please let me know where you would like it, and I could send a pull request.

**Comment by aldur** [comment]
Yes documentation would be great and we're definitely interested :)

If you'd like to submit a PR you can place the docs in a `docs` directory and the scripts in a `examples` directory.
Let me know if you need any help/other info.

**Comment by ramanshah** [comment]
Great, I'll keep you posted!
