### ISSUE TITLE
Switch for never delete?

### ISSUE THREAD

**Issue by StefanKrauth** [unbit/sftpclone#11]
Hello,
would it be possible to provide a switch to disable the remote side deletion? I would like to keep a small local directory with incremental backups from the last months. But on the backup server I would like to "not delete" older backups. It should just add the new files. (like rsync without the --delete switch)

Best Regards,
Stefan

**Comment by aldur** [comment]
Hi, I've pushed an update in the develop branch that should implement it.

It's still not on PyPi, but you can try it with the following commands:
```bash
$ git clone https://github.com/unbit/sftpclone.git
$ cd sftpclone
$ git checkout develop
$ python setup.py develop
$ sftpclone -t # ... and the usual command
```
Let me know if you have any feedback.

**Comment by StefanKrauth** [comment]
Wow, that was fast. I'm testing it right now. Thanks!

**Comment by StefanKrauth** [comment]
Hi, I can confirm that the -t parameter works.

I create a couple of files and folders inside the backup directly. After running sftpclone with the -t switch  all files and folders were still present. Running sftpclone without the the -t switch deletes these files again.

Thank you!

Best Regards,
Stefan
