### ISSUE TITLE
Upload create breaks

### ISSUE THREAD

**Issue by StefanKrauth** [unbit/sftpclone#12]
Hi,
sorry for creating another issue today. I'm testing the develop branch at the moment. The first 8GB of files have been transferred just fine. Then an error occurs reproducible...

![sftpclone_errdbg](https://cloud.githubusercontent.com/assets/663776/11041607/185fba10-8713-11e5-8f22-4faf5d47d55f.png)

![sftpclone_errdbg_1](https://cloud.githubusercontent.com/assets/663776/11041606/185f15b0-8713-11e5-9fd0-ac62a107a4a1.png)

This is a normal jpg file like all the other ones in the same directory.

I have now temporarily removed this directory to see if it breaks again (still running).

Update: Yes, it breaks again without this thumb directory. I've run sftpclone with the parameters -f -t.

Best Regards,
Stefan

**Comment by aldur** [comment]
It is a Unicode related problem, I'll dig into it. What Python version?

**Comment by StefanKrauth** [comment]
I'm using Python 2.7.9.

**Comment by StefanKrauth** [comment]
I ran it again without -t and -f it broke again. I think the issue above is related to the -t switch as the error looks different now.

Switch -t -f: error above
Switch -t: error above
Switch -f: (currently running)
Switch none: error below

![bildschirmfoto 2015-11-09 um 21 23 36](https://cloud.githubusercontent.com/assets/663776/11045556/6653bf90-8728-11e5-992f-ca88ab2cba1e.jpg)

**Comment by aldur** [comment]
Thanks again for your report.
The last error should be already fixed here: 13ea41971f97e1a9d6fa16b6dff2cf8aaf84d4a9.
Generally speaking, on Python 2 that exception means that an IOError happened (and the FileNotFoundError is indeed aliased to IOError).

I'm investigating the previous one, I'll report back.
Does it consistently break on the same path? And if so, could you please paste it so that I can fake it locally?

**Comment by StefanKrauth** [comment]
Yes and no. Currently it is breaking somewhere else. But reproducable at the same path. Tonight a backup update was running, so the folders might have changed.

Today it breaks here:
![sftpclone_err_a](https://cloud.githubusercontent.com/assets/663776/11064704/16ea662e-87bf-11e5-9aee-b5105fd2fcbb.png)

You can find the information around the directory structure here:
http://srv.skrauth.de/files/sftpclone_err.txt

This is an archive of all files starting at the misc directory:
http://srv.skrauth.de/files/misc.tar.bz2

Thanks again & best regards,
Stefan

**Comment by StefanKrauth** [comment]
Hmm, I fixed the problem by hammering in utf-8 as default encoding.

```
import sys
reload(sys)
sys.setdefaultencoding("utf-8")
```

It seems to work in my case. No crash yet, but obviously a hakish solution.

Reference reading: http://stackoverflow.com/questions/3828723/why-we-need-sys-setdefaultencodingutf-8-in-a-py-script

**Comment by aldur** [comment]
Yes, I've seen that too. It's a worst case solution, but if I can I'd like to find a more elegant version.
Anyway, it should be noted that the problem disappears by itself in the Python 3 version.

**Comment by StefanKrauth** [comment]
This is fine for me too. Can I instruct setup.py to use python3?
Alternatively: Is it enough to change the shebang in /usr/local/bin/sftpclone to `#!/usr/bin/python3`?

**Comment by StefanKrauth** [comment]
Ah I figured, just calling it with python3 - very convinient. Maybe just fix it with a note in the readme...?

**Comment by aldur** [comment]
I almost always use virtualenvs, but for the `setup.py` file it should be sufficient to launch it with `python3 setup.py`. 
The shebang trick should work too, but in many environments could select an unexpected python version (e.g. in a Python 2 virtualenv it would select the system v3 interpreter).

And yes, if I won't fix it I'll add it to the `README`.

**Comment by StefanKrauth** [comment]
Nope... python3:

![sftpclone_err_p3](https://cloud.githubusercontent.com/assets/663776/11067720/5b0c9520-87ce-11e5-903c-c2cf9f9cf4a2.png)

(it's the original error again. I reverted the backup from tonight to verify this reproducability)

**Comment by StefanKrauth** [comment]
What about setting `PYTHONIOENCODING=UTF-8` in the virtualenv?

**Comment by aldur** [comment]
Does `PYTHONIOENCODING=UTF-8` fix the problem?
I'm having troubles reproducing it, I've added a few tests (ac9bae83faac5ec43838c63ccb16c0c43e9bd45c) to handle non-ascii characters and they pass.

**Comment by StefanKrauth** [comment]
`LC_CTYPE is unset. `LANG` is currently set to `C`.

I have played around with `LANG` and `LC_ALL` earlier. I've set both to `C`, `de_DE.UTF-8` and `en_US.UTF-8`. No change in behavior.

`PYTHONIOENCODING=UTF-8` did not fix the problem when I set it in my environment. However you mentioned virtualenv, so my assumption was, that my user environment is not used.

**Comment by StefanKrauth** [comment]
No behavior change with the latest verison.

![scp_env](https://cloud.githubusercontent.com/assets/663776/11097696/045010b2-88a1-11e5-8e90-6b234f7d1bec.png)

![scp_err](https://cloud.githubusercontent.com/assets/663776/11097700/08b62b00-88a1-11e5-91a2-0210363d80bd.png)

**Comment by aldur** [comment]
To be sure about `PYTHONIOENCODING=UTF-8`, regardless of environment or virtualenv, it should be enough to launch `sftpclone` as follows:

```bash
PYTHONIOENCODING=UTF-8 sftpclone ...
```

Could you provide a few more info? Sorry about all this :)
```
$ python # inside the virtualenv and outside, i.e. for both 2 and 3 Python versions
>>> import sys
>>> print(sys.getfilesystemencoding())
```

I'm analyzing the previous path (`root/BACKUP_OLDSERVER/mnt/docroot/http/caro-busch.www/wp-content/uploads/photo-gallery/beauty_fashion/thumb/angela-16.jpg`). The error seems to happen on character #115 `-`. 
I've dug through paramiko's files and it only tries to encode the received buffer, so there seems not to be anything on that side.

Are you sure to be using latest version, BTW? 
[Line #390 from latest commit](https://github.com/unbit/sftpclone/blob/ac9bae83faac5ec43838c63ccb16c0c43e9bd45c/sftpclone/sftpclone.py#L390) seems to be different wrt the one indicated in the logs.

Another thing I'm noticing (from [here](https://github.com/unbit/sftpclone/blob/ac9bae83faac5ec43838c63ccb16c0c43e9bd45c/sftpclone/sftpclone.py#L407)):

```python
        # sftpclone.py:L407
        local_path = join(self.local_path, relative_path, f)  # executed
        
        # ...

        # sftpclone.py:L407
        remote_path = join(self.remote_path, relative_path, f)  # fails, but `relative_path` and `f` didn't change
````
I guess your server path doesn't contain non-ascii characters, so it seems strange.

**Comment by StefanKrauth** [comment]
The screenshot was taken from the previous run. Sorry about that. But besides the line numbers, the error didn't change.

Okay, next one...  executing `PYTHONIOENCODING=UTF-8 sftpclone -f -t `

![current](https://cloud.githubusercontent.com/assets/663776/11098214/c0d3952c-88a3-11e5-98ee-6c88ce9509ac.png)

Well, maybe I should stop my backup. I would have to roll back the backup again to reach to the error from before yesterday.

I'm offline for the next 2 hours. If you want, I can set up a screen sharing session (teamviewer?) and you can look at it on my machine directly? If you can't reproduce it, this is probably easier this way.

**Comment by StefanKrauth** [comment]
For me it is reproducible with the `misc.tar.bz2` file I've sent you the link to. I'll try to reproduce it again on another machine when I'm home.

**Comment by StefanKrauth** [comment]
Hi,
I've added `print(sys.getfilesystemencoding())` under the imports. The output is:

```
ANSI_X3.4-1968
```

**Comment by StefanKrauth** [comment]
The output above helped me to find [this article](http://stackoverflow.com/questions/2596714/why-does-python-print-unicode-characters-when-the-default-encoding-is-ascii/21968640#21968640).

Indeed when I set `LC_CTYPE` to de_DE.UTF-8, `sys.getfilesystemencoding()` returns "UTF-8".

Unfortunately it still does not fix the error. It still breaks with the same `UnicodeDecodeError: 'ascii'` error.

**Comment by aldur** [comment]
OK, so what happens after merging #13? 
All is well on Python 2, and what about Python 3?
I'm going to setup some more tests with a structure alike to the `misc.tar.bz2` file posted here.

**Comment by StefanKrauth** [comment]
All well in python2. I transferred about 60GB of files with the fix. I'll do another batch of files with python3 later on.

For the test, you only need a subfolder and a file in it with an unicode character. The file creating trouble was "EBG_Elektronik_Sertifika_Hizmet_Sağlayıcısı.pem".
![utffile](https://cloud.githubusercontent.com/assets/663776/11120827/9f71b54e-8952-11e5-9634-52eb37657957.png)

I have to test if the created files actually are okay and if the -t parameter did what it's supposed to do.

I'll report back as soon.

**Comment by StefanKrauth** [comment]
Python3 makes trouble with mixing byte strings and unicode (which works in python2). So it looks like it is more strikt in this regard. Also encoding the filename fixes this. I tried to do as less as possible in the patch. That's why I didn't do it before.

**Comment by aldur** [comment]
The weird thing is that I already had a test for creating unicode filenames (ac9bae83faac5ec43838c63ccb16c0c43e9bd45c) on the local/remote side and I had no problem. This led me thinking to the environment problem.
Anyway, can you try again after pulling this change? (4fa997316b5c37b19f57bebd94d7f88966bd6cfd)

**Comment by StefanKrauth** [comment]
Oh cool. Yes, this totally works!

![result](https://cloud.githubusercontent.com/assets/663776/11121454/3c55435a-8956-11e5-8413-41cc4c3d0e65.png)

**Comment by aldur** [comment]
Great, perfect. :+1:

**Comment by StefanKrauth** [comment]
Thank you very much! I'll report about my -t test in the other issue.
