### ISSUE TITLE
Crash if the ssh_config entry contains "IdentityFile"

### ISSUE THREAD

**Issue by slalik** [unbit/sftpclone#15]
Hello,
when I run
```
# sftpclone /root/test/ backup:/root_backup/test
```
with `/root/.ssh/config`:
```
Host backup
HostName ...
User ...
IdentityFile ~/.ssh/id_rsa_backup
```
sftpclones crashes as follows:
```
Traceback (most recent call last):
  File "/usr/bin/sftpclone", line 7, in <module>
    sftpclone()
  File "/usr/lib64/python2.7/site-packages/sftpclone/sftpclone.py", line 728, in main
    **kwargs
  File "/usr/lib64/python2.7/site-packages/sftpclone/sftpclone.py", line 162, in __init__
    key = os.path.expanduser(key)
  File "/usr/lib64/python2.7/posixpath.py", line 261, in expanduser
    if not path.startswith('~'):
AttributeError: 'list' object has no attribute 'startswith'
```
Without the "IdentityFile" in /root/.ssh/config sftpclone works normally.
My settings:
python-2.7.5
sftpclone-1.1
paramiko-1.16.0
ecdsa-0.13
pycrypto-2.6.1

There is (rather old) bug in duplicity
https://bugs.launchpad.net/duplicity/+bug/1156746
which looks similar.  In that case the problem was:
> The problem is that starting with version 1.10.0, Paramiko's SSH config parser allows multiple IdentityFile options per host, meaning that SSHParamikoBackend.config['identityfile'] is *always* a list now
> (earlier versions simply returned a string).

**Comment by aldur** [comment]
Thanks for reporting, I'll commit a fix ASAP :)

**Comment by aldur** [comment]
@slalik, can you check (using 9fec480) that everything is fine for your work cases?

**Comment by slalik** [comment]
Yes, it works flawlessly.  Thank you for quick fixing!

BTW, I'd suggest a minor improvement  for the README in the "ssh_config
compatibility" section, namely:
```
Hostname --> HostName
Username --> User
```

**Comment by aldur** [comment]
Done too, thanks for spotting it :)
