### ISSUE TITLE
"@" not allowed to be in the username, password

### ISSUE THREAD

**Issue by longbored** [unbit/sftpclone#20]
In the SFTPClone class, if the username or password contains the "@" character, the username/hostname is parsed incorrectly. Here's the change I made on line 100 to sftpclone.py:

`hostname, username = [k[::-1] for k in remote_url[::-1].split('@',1)]`

Unfortunately, my amateur skills can't figure it out for the subsequent 'else'.

**Comment by aldur** [comment]
Hi, thanks for reporting and sorry for the long time.
Can you try with the upstream version? I should have fixed your issue.
