### ISSUE TITLE
Agent support doesn't work if there is more than one SSH-key loaded into the agent

### ISSUE THREAD

**Issue by derkork** [unbit/sftpclone#21]
When I try to use agent support and more than one SSH key is loaded into the agent, I get this stacktrace:

```
 Traceback (most recent call last):
  File "/usr/local/bin/sftpclone", line 7, in <module>
    sftpclone()
  File "/usr/local/lib/python2.7/dist-packages/sftpclone/sftpclone.py", line 742, in main
    **kwargs
  File "/usr/local/lib/python2.7/dist-packages/sftpclone/sftpclone.py", line 146, in __init__
    agent_keys.append(*agent.get_keys())
TypeError: append() takes exactly one argument (2 given)
```

These keys are loaded into the agent:

```
$ ssh-add -l
1024 68:80xxxxxxx/Users/kork/.ssh/id_dsa (DSA)
4096 57:69:xxxxxx /Users/kork/.ssh/id_rsa_new (RSA)

```

**Comment by unbit** [comment]
@derkork  you try this patch ? 

https://github.com/unbit/sftpclone/commit/44cc970b3e46031f3451e4908ce38e76be74ffc7

@aldur what about adding a test for this specific case ?

**Comment by aldur** [comment]
Yes, sounds like a great idea.
I'll do it for this one and #20 as soon as I have a moment 👍

**Comment by aldur** [comment]
@unbit 558f272f0d13168fc6fc93f5e7dc3d00e9767927 adds a new test for SSH agent and its keys.
Merge at will :)
