### ISSUE TITLE
Support of proxycommand

### ISSUE THREAD

**Issue by noqqe** [unbit/sftpclone#23]
ProxyCommand settings are being ignored even if you put `ssh_config_path` in the SFTPClone instance.

```
Host foobar
 hostname host.example.com
 proxycommand /usr/local/bin/corkscrew proxy.example.com 3128 %h %p ~/.corkscrewauth
 port 22
 user foo
```

**Comment by aldur** [comment]
Thanks for the report.
Could you try with [this branch](https://github.com/unbit/sftpclone/tree/proxy_command)?

**Comment by noqqe** [comment]
@aldur Wow, nice one! Works fine.

Thanks for the quick fix.

**Comment by unbit** [comment]
@aldur i think it is time to make a new release on pypi ;)

**Comment by aldur** [comment]
Yes, working on it right now. I'm fixing a couple of issues with one specific test, then I'll update the metadata and bump the version number.
In the meantime, I plan to also merge [this branch](https://github.com/unbit/sftpclone/tree/attempt_to_fix_multiple_keys_in_agent).

**Comment by aldur** [comment]
Done, version 1.2 is live on PyPi.
