### ISSUE TITLE
Feature request: Allow for creating a remote folder

### ISSUE THREAD

**Issue by janusheide** [unbit/sftpclone#28]
We have a small chain for generating and uploading some documentation where we tried this tool for the upload step. But when uploading into a folder on the remote that does not exists I get the following error:

"... ERROR - Error while opening remote folder. Are you sure it does exist?"

Would it make sense to allow the creation of a remote target folder if it does not already exist? 
If so how would be a good way to go about it, and should we try to open a pull request - if we manage to come up with a working change?

**Comment by aldur** [comment]
Yes, I think that it would definitely make sense, as your use case shows.
A pull request would be awesome and a good starting point is probably [here](https://github.com/unbit/sftpclone/blob/32ce07802b0e800276de5cd290acea9939bab98e/sftpclone/sftpclone.py#L604), i.e. at the line that is creating the error.

One way to proceed could be as follows:
- On error, try creating the remote folder.
- Log its creation to the user to keep her informed.
- (Maybe) Add a command line flag to enable this behaviour.

I'm here if you need any help :)

**Comment by janusheide** [comment]
Great will give it a try.
